{{- if .Values.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whisperx-fastapi.fullname" . }}-hf-token
  labels:
    {{- include "whisperx-fastapi.labels" . | nindent 4 }}
type: Opaque
data:
  hf-token: {{ .Values.hfToken | b64enc | quote }}
{{- end }}
